-- DropForeignKey
ALTER TABLE `MonthlyChurnMetric` DROP FOREIGN KEY `MonthlyChurnMetric_clubId_fkey`;

-- AlterTable
ALTER TABLE `ChurnEvent` DROP COLUMN `metaJson`,
    MODIFY `eventType` ENUM('TRAINING_COMPLETED', 'LIVE_SESSION_ATTENDED', 'FEED_ENGAGED', 'TRAINING_PENALTY_TIER1', 'TRAINING_PENALTY_TIER2', 'TRAINING_PENALTY_TIER3', 'LIVE_PENALTY_TIER1', 'LIVE_PENALTY_TIER2', 'LIVE_PENALTY_TIER3', 'FEED_PENALTY_TIER1', 'FEED_PENALTY_TIER2', 'FEED_PENALTY_TIER3', 'STATUS_CHANGED') NOT NULL;

-- AlterTable
ALTER TABLE `SessionBooking` DROP COLUMN `bookingStatus`;

-- AlterTable
ALTER TABLE `User` DROP COLUMN `subscription`,
    ADD COLUMN `subscriptionMethod` ENUM('ADMIN_GRANTED', 'STRIPE_PAID') NOT NULL DEFAULT 'ADMIN_GRANTED';

-- DropTable
DROP TABLE `MonthlyChurnMetric`;

